### ISSUE TITLE
Switch the documentation to Markdown formatting

### ISSUE THREAD

**Issue by AleKoure** [AleKoure/Rigma#12]
Switch the documentation to Markdown formatting

**Comment by elipousson** [comment]
I think this is good to close with #9

**Comment by AleKoure** [comment]
I reopened this as I moved it to develop. Why do we need this?

**Comment by elipousson** [comment]
Closed by #23 but, to provide a long-delayed answer, I think Markdown formatted Roxygen markup is faster/easier to read and write. I think regular Roxygen still works so you can always write it whichever way you prefer and periodically run `roxygen2md::roxygen2md()` to convert the docs to Markdown formatting.
